version: "2"
formatters:
  enable:
    - gofmt
    - goimports
linters:
  enable:
    - bodyclose
  settings:
    errcheck:
      check-blank: false
    staticcheck:
      checks:
        - "all"
        - "-ST*"
        - "-QF*"
  exclusions:
    rules:
      - path: "_test\\.go$"
        linters:
          - errcheck
      - path: "scrutiny_repository_migrations\\.go$"
        text: "SA1019"
        linters:
          - staticcheck
      - text: "Error return value of .+Close.* is not checked"
        linters:
          - errcheck
      - text: "Error return value of `fmt\\.Fprint"
        linters:
          - errcheck
      - text: "Error return value of `\\(\\*github\\.com/fatih/color\\.Color\\)\\.Fprintf`"
        linters:
          - errcheck
